server:
  port: 8098    #Puerto por defecto en donde se inicia el servidor
 
eureka:         #Informa sobre los detalles del servidor Eureka y su tiempo de actualización
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:     
  application:
    name: cliente-service   #Nombre del servicio actual que utilizará el servidor de eureka
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.example.howtodoinjava: DEBUG